DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS articles;
DROP TABLE IF EXISTS orders_articles;
DROP TABLE IF EXISTS home;
DROP TABLE IF EXISTS mangas;
DROP TABLE IF EXISTS contact;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  email VARCHAR(50) NOT NULL UNIQUE,  
  password VARCHAR(250) NOT NULL,
  phone VARCHAR(15) NOT NULL UNIQUE,
  address VARCHAR(50) NOT NULL,
  city VARCHAR(30) NOT NULL,
  role VARCHAR(10) NOT NULL CHECK (role IN ('user', 'admin'))
);

INSERT INTO user (first_name, last_name, email, password, phone, address, city, role) VALUES 
('Mato', 'NGUAYILA', 'matomina.nguayila@gmail.com', 'Orly94', '07-54-69-32-58', '1 rue du clos dion', 'Montereau-Fault-Yonne', 'admin'),
('Cynthia', 'DAUVERNE', 'cynthia.dauverne@gmail.com', 'Monterau77', '07-55-69-32-58', '1 rue du clos dion', 'Montereau-Fault-Yonne', 'user'),
('Hakim', 'BOUDERE', 'hakim.boudere@gmail.com', 'Paris75', '07-56-69-32-58', '1 rue de la paix', 'Paris', 'user'),
('Billal', 'ZEBIR', 'billal.zerbir@gmail.com', 'Pantin93', '07-57-69-32-58', '1 rue de courcelle', 'Pantin', 'user'),
('Zeyna', 'SIDIBE', 'zeyna.sidibe@gmail.com', 'Cachan94', '07-58-69-32-58', '1 rue pasteur', 'Cachan', 'user'),
('Alfred', 'Macdy', 'alfred.macdy@gmail.com', 'Evry91', '07-59-69-32-58', '1 allée de la brume', 'Evry', 'user'),
('Moussa', 'DIOP', 'moussa.diop@gmail.com', 'Coulommier77', '07-60-69-32-58', '1 rue des champs', 'Coulommiers', 'user');

/* ======================================================================================= */
/* ======================================================================================= */

CREATE TABLE orders (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  users_id INTEGER NOT NULL,
  total_amount FLOAT,  
  order_date DATE NOT NULL,
  status VARCHAR(15) NOT NULL CHECK (status IN ('en attente', 'payée', 'expédiée','livrée', 'annulée')),

  FOREIGN KEY (users_id) REFERENCES user(id)
);

INSERT INTO orders (users_id, total_amount, order_date, status) VALUES 
(2, 356, '2025-05-10', 'en attente'),
(2, 250, '2025-05-11', 'payée'),
(3, 425, '2025-05-12', 'expédiée'),
(4, 99, '2025-05-13', 'livrée'),
(5, 199, '2025-05-14', 'annulée');

/* ======================================================================================= */
/* ======================================================================================= */

CREATE TABLE articles (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(50) NOT NULL,
  genres VARCHAR(15) NOT NULL CHECK (genres IN ('manga', 'figurine', 'textiles','vaisselle', 'goodies')),
  image TEXT NOT NULL,
  created_date DATE DEFAULT GETDATE(),  
  price FLOAT NOT NULL
);

INSERT INTO articles (name, genres, image, created_date, price) VALUES 
('Dragon Ball','manga','Image/Dragon-Ball-Tome.jpeg',GETDATE(),6.90),
('Dragon Ball Z','manga','Image/Dragon-Ball-Z-Tome.jpeg',GETDATE(),7.10),
('One Piece','manga','Image/One-Piece-Tome.jpeg',GETDATE(),6.90),
('Naruto','manga','Image/Naruto-Tome.jpeg',GETDATE(),7.50),
('Naruto Shippuden','manga','Image/Naruto-Shippuden.jpeg',GETDATE(),7.90),
('Bleach','manga','Image/Bleach-Tome.jpeg',GETDATE(),7.30),
('Pokémon','manga','Image/Pokemon-Tome.jpeg',GETDATE(),6.50),
('Sailor Moon','manga','Image/Sailor-Moon-Tome.jpeg',GETDATE(),8.00),
('Ranma ½','manga','Image/Ranma-1-2-Tome.jpeg',GETDATE(),7.40),
('Détective Conan','manga','Image/Détective-Conan-Tome.jpeg',GETDATE(),7.60),
('Yu-Gi-Oh','manga','Image/Yu-Gi-Oh-Tome.jpeg',GETDATE(),7.00),
('Great Teacher Onizuka','manga','Image/Great-Teacher-Onizuka-Tome.jpeg',GETDATE(),8.20),
('Death Note','manga','Image/Death-Note-Tome.jpeg',GETDATE(),6.90),
('Hajime No Ippo','manga','Image/Hajime-No-Ippo-Tome.jpeg',GETDATE(),8.90),
('Saint Seiya','manga','Image/Saint-Seya-Tome.jpeg',GETDATE(),7.20),
('Ken le Survivant','manga','Image/Ken-Le-Survivant-Tome.jpeg',GETDATE(),8.50),
('City Hunter','manga','Image/City-Hunter-Tome.jpeg',GETDATE(),7.60),
('Gundam Wing','manga','Image/Gundam-Wing-Tome.jpeg',GETDATE(),8.00),
('Full Metal Alchemist','manga','Image/Full-Metal-Tome.jpeg',GETDATE(),8.00),
('Fairy Tail','manga','Image/Fairy-Tail-Tome.jpeg',GETDATE(),7.50),
('One Punch Man','manga','Image/One-Punch-Man-Tome.jpeg',GETDATE(),8.50),
('Afro Samouraï','manga','Image/Afro-Samourai-Tome.jpeg',GETDATE(),9.10),
('99 Renforced Wooden Stick','manga','Image/99-Renforced-Wooden-Stick.jpeg',GETDATE(),10.00),
('Moi Slime','manga','Image/Moi-Slime-Tome.jpeg',GETDATE(),7.80),
('Figurine Aokiji','goodies','Image/Gif-figurine-Aokiji.gif',GETDATE(),25.00),
('Mug Dragon Ball Z','goodies','Image/Gif-Mug-Bdz.webp',GETDATE(),12.00),
('Lot de figurine','goodies','Image/Gif-Figurine.webp',GETDATE(),180.00),
('Mug Sasuke','goodies','Image/Gif-Mug-Sasuke.webp',GETDATE(),12.50),
('Figurine Alma Feri','goodies','Image/Gif-Figurine2.gif',GETDATE(),20.00),
('Mug Yu-Gi-Oh','goodies','Image/Mug-YuGiOh-thermo-actif.gif',GETDATE(),14.00),
('Figurine Terrece','goodies','Image/Gif-Figurine-3.webp',GETDATE(),22.00),
('One Piece','manga','Image/One-Piece-Tome.jpeg',GETDATE(),7.80),
('Naruto-Shippuden','manga','Image/Naruto-Shippuden.jpeg',GETDATE(),7.80),
('Jujutsu-Kaisen','manga','Image/Jujutsu-Kaisen-Tome.jpeg',GETDATE(),7.80),
('Demon-Slayer','manga','Image/Demon-Slayer-Tome.jpeg',GETDATE(),7.80),
('Black-Clover','manga','Image/Black-Clover-Tome.jpeg',GETDATE(),7.80),
('Death-Note','manga','Image/Death-Note-Tome.jpeg',GETDATE(),7.80),
('Solo-Leveling','manga','Image/Solo-Leveling-Tome.jpeg',GETDATE(),7.80),
('My-Hero-Academia','manga','Image/My-Hero-Academia-Tome.jpeg',GETDATE(),7.80),
('Hajime-No-Ippo','manga','Image/Hajime-No-Ippo-Tome.jpeg',GETDATE(),7.80),
('Kaiju-N°8','manga','Image/Kaiju-N°8-Tome.jpeg',GETDATE(),7.80),
('Dandadan','manga','Image/Dandadan-Tome.jpeg',GETDATE(),7.80),
('Edens-Zero','manga','Image/Edens-Zero-Tome.jpeg',GETDATE(),7.80),
('Sakamoto-Days','manga','Image/Sakamoto-Days-Tome.jpeg',GETDATE(),7.80),
('One-Punch-Man','manga','Image/One-Punch-Man-Tome.jpeg',GETDATE(),7.80),
('Full-Metal','manga','Image/Full-Metal-Tome.jpeg',GETDATE(),7.80),
('Dr-Stone','manga','Image/Dr-Stone-Tome.jpeg',GETDATE(),7.80),
('Afro-Samourai','manga','Image/Afro-Samourai-tome.jpeg',GETDATE(),7.80),
('Fairy-Tail','manga','Image/Fairy-Tail-Tome.jpeg',GETDATE(),7.80),
('Hunter-X-Hunter','manga','Image/Hunter-X-Hunter-Tome.jpeg',GETDATE(),7.80),
('99-Renforced-Wooden-Stick','manga','Image/99-Renforced-Wooden-Stick.jpeg',GETDATE(),7.80),
('Moi-Quand-Je-Me-Reincarne-En-Slime','manga','Image/Moi-Slime-Tome.jpeg',GETDATE(),7.80),
('Gundam-Wing','manga','Image/Gundam-Wing-Tome.jpeg',GETDATE(),7.80),
('City-Hunter- Nicky-Larson','manga','Image/City-Hunter-Tome.jpeg',GETDATE(),7.80),
('Ranma1/2','manga','Image/Ranma-1-2-Tome.jpeg',GETDATE(),7.80),
('Shangri-La-Frontier','manga','Image/Shangri-La-Frontier.jpeg',GETDATE(),7.80),
('Gachiakuta','manga','Image/Gachiakuta-Tome.jpeg',GETDATE(),7.80),
('Great-Teacher-Onizuka','manga','Image/Great-Teacger-Onizuka-Tome.jpeg',GETDATE(),7.80),
('Yu-Gi-Oh','manga','Image/Yu-Gi-Oh-Tome.jpeg',GETDATE(),7.80),
('Détective-Conan','manga','Image/Détective-Conan-Tome.jpeg',GETDATE(),7.80),
('Ken-Le-Survivant','manga','Image/Ken-Le-Survivant-Tome.jpeg',GETDATE(),7.80),
('Saint-Seya-Les-Chevaliers-Du-Zodiaque','manga','Image/Saint-Seya-Tome.jpeg',GETDATE(),7.80),
('Sailor-Moon','manga','Image/Sailor-Moon-Tome.jpeg',GETDATE(),7.80),
('Dragon-Ball-Z','manga','Image/Dragon-Ball-Z-Tome.jpeg',GETDATE(),7.80),
('Naruto','manga','Image/Naruto-Tome.jpeg',GETDATE(),7.80),
('Dragon-Ball','manga','Image/Dragon-Ball-Tome.jpeg',GETDATE(),7.80),
('Bleach','manga','Image/Bleach-Tome.jpeg',GETDATE(),7.80),
('Pop Naruto - Edition limitée','goodies','Image/Pop Naruto.jpeg',GETDATE(),29.90),
('Figurine Itachi + Peluche Kuruma','goodies','Image/Figurine Itachi + Peluche Kuruma.jpeg',GETDATE(),52.50),
('Figurine Jiraya','goodies','Image/Figurine Jiraya.jpeg',GETDATE(),25.90),
('Figurine Naruto Mode Emite','goodies','Image/Figurine Naruto Mode Emite.jpeg',GETDATE(),35.90),
('Mug Naruto Kakashi','goodies','Image/Mug Naruto.jpg',GETDATE(),9.90),
('Jeu de société Naruto','goodies','Image/Jeu de société Naruto.jpeg',GETDATE(),56.50),
('Katana Konoha','goodies','Image/Katana Naruto.jpeg',GETDATE(),74.90),
('Sac Naruto','goodies','Image/Sac Naruto.jpeg',GETDATE(),34.90),
('Porte clé Pop Naruto','goodies','Image/Porte clé Pop Naruto.jpeg',GETDATE(),14.90),
('Mug Naruto Equipe 7','goodies','Image/Mug Naruto Equipe 7.jpeg',GETDATE(),9.90),
('Bandeau Sasuke','goodies','Image/Bandeau Naruto.jpeg',GETDATE(),44.90),
('Kunai Naruto','goodies','Image/Kunai Naruto.jpeg',GETDATE(),54.90),
('Figurine Satoru Gojo','goodies','Image/Figurine Satoru Gojo.jpeg',GETDATE(),17.80),
('Lampe Satoru Gojo','goodies','Image/Lampe Satoru Gojo.jpeg',GETDATE(),27.80),
('Mug Itadori','goodies','Image/Mug Itadori 1.jpg',GETDATE(),9.80),
('Figurine Pop Sukuna','goodies','Image/Figurin Pop Sukuna.jpeg',GETDATE(),27.80),
('Sac à Dos Jujutsu Kaisen','goodies','Image/Sac à Dos Jujutsu Kaisen.jpeg',GETDATE(),47.80),
('Lots Bagues Jujutsu Kaisen','goodies','Image/Lots Bagues Jujutsu Kaisen.jpeg',GETDATE(),37.80),
('Figurine Pop Megumi','goodies','Image/Figurine Pop Megumi.jpeg',GETDATE(),27.80),
('Lots Porte Clé Jujutsu Kaisen','goodies','Image/Lots Porte Clé Jujutsu Kaisen.jpeg',GETDATE(),17.80),
('Mug Satoru Gojo','goodies','Image/Mug Satoru Gojo.jpeg',GETDATE(),18.80),
('Figurine Led Luffy Gear 5','goodies','Image/Figurine Led Luffy Gear 5.jpeg',GETDATE(),67.80),
('Bateau Thousant Sunny','goodies','Image/Bateau Thousant Sunny.jpeg',GETDATE(),87.80),
('Coffre au Trésor One Piece','goodies','Image/Coffre au Trésor One Piece.jpeg',GETDATE(),97.80),
('Figurine Pop Luffy','goodies','Image/Figurine Pop Luffy.jpeg',GETDATE(),27.80),
('Figurine Ace','goodies','Image/Figurine Ace.jpeg',GETDATE(),27.80),
('Verre One Piece','goodies','Image/Verre One Piece.jpeg',GETDATE(),7.80),
('Figure Jinbe','goodies','Image/Figure Jinbe.jpeg',GETDATE(),37.80),
('Figurine Ener','goodies','Image/Figurine Ener.jpeg',GETDATE(),37.80),
('Fruits des Demons','goodies','Image/Fruits des Demons.jpeg',GETDATE(),47.80),
('Figurine Pop Kaido','goodies','Image/Figurine Pop Kaido.jpeg',GETDATE(),27.80),
('Figurine Luffy Gear 5','goodies','Image/Figurine Luffy Gear 5.jpeg',GETDATE(),39.80),
('Figurine Mihawk','goodies','Image/Figurine Mihawk.jpeg',GETDATE(),39.80),
('Figurine Pop Zoro','goodies','Image/Figurine Pop Zoro.jpeg',GETDATE(),27.80),
('Figurine Barbe Noir','goodies','Image/Figurine Barbe Noir.jpeg',GETDATE(),37.80),
('Peluche Fruit du Démon','goodies','Image/Peluche Fruit du Demon.jpeg',GETDATE(),29.80),
('Chapeau Luffy','goodies','Image/Chapeau Luffy.jpeg',GETDATE(),54.80),
('Support Portable Luffy Gear 5','goodies','Image/Support Portable Luffy Gear 5.jpeg',GETDATE(),25.80),
('Coque Portable One Piece','goodies','Image/Coque Portable.jpeg',GETDATE(),17.80),
('Sac à Dos One Piece','goodies','Image/Sac à Dos One Piece.jpeg',GETDATE(),45.80),
('Lots Mugs One Piece','goodies','Image/Lots Mugs One Piece.jpeg',GETDATE(),77.80),
('Lampe Luffy Gear 5','goodies','Image/Lampe Luffy Gear 5.jpeg',GETDATE(),44.80),
('Figurine Gear 5 Luffy','goodies','Image/Figurine Gear 5 Luffy.jpg',GETDATE(),55.80),
('Figurine Gol D Roger','goodies','Image/Figurine Gol D Roger.jpeg',GETDATE(),44.80),
('Bague One Piece','goodies','Image/Bague One Piece.jpeg',GETDATE(),25.80),
('Porte Feuille One Piece','goodies','Image/Porte Feuille One Piece.jpeg',GETDATE(),45.80),
('Manette PS5 One Piece','goodies','Image/Manette PS5 One Piece.jpeg',GETDATE(),125.80),
('Figurine Tanjiro','goodies','Image/Figurine Tenjuro.jpeg',GETDATE(),37.90),
('Figurine Pop Tanjiro Nezuko','goodies','Image/Figurine Pop Tanjiro Nezuko.jpeg',GETDATE(),39.80),
('Lots Portes Clés Demon Slayer','goodies','Image/Lots Porte Clé Demon Slayer.jpeg',GETDATE(),27.80),
('Figurine Nezuko','goodies','Image/Figurine Nezuko.jpeg',GETDATE(),29.90),
('Figurine Inosuke','goodies','Image/Figurine Inosuke.jpeg',GETDATE(),29.80),
('Katana Tanjiro','goodies','Image/Katana Tanjiro.jpg',GETDATE(),107.80),
('Figurine Sabito','goodies','Image/Figurine Sabito.jpeg',GETDATE(),29.80),
('Figurine Tengen','goodies','Image/Figurine Tengen.jpeg',GETDATE(),29.80),
('Figurine Tomyoka','goodies','Image/Figurine Tomyoka.jpeg',GETDATE(),29.80),
('Figurine Muichiro','goodies','Image/Figurine Muichiro.jpeg',GETDATE(),29.80),
('Figurine Sanemi','goodies','Image/Figurine Sanemi.jpeg',GETDATE(),29.80),
('Figurine Kanroji','goodies','Image/Figurine Kanroji.jpg',GETDATE(),29.80),
('Figurine Zenitsu','goodies','Image/Figurine Zenitsu.jpeg',GETDATE(),29.80),
('Coffret 15 Piece Demon Slayer','goodies','Image/Coffret 15 Piece Demon Slayer.jpeg',GETDATE(),79.80),
('Coffret Demon Slayer','goodies','Image/Coffret Demon Slayer.jpeg',GETDATE(),59.80),
('Figurine Pop Nezuko','goodies','Image/Figurine Pop Nezuko.jpeg',GETDATE(),29.80),
('Figurine Pop Tanjiro Feu','goodies','Image/Figurine Pop Tanjiro Feu.jpeg',GETDATE(),29.80),
('Figurine Pop Kiojuro','goodies','Image/Figurine Kiojuro.jpeg',GETDATE(),29.80),
('Figurine Pop Tanjiro','goodies','Image/Figurine Pop Tanjiro.jpeg',GETDATE(),29.80),
('Figurine Pop Goku Ultra Instinct','goodies','Image/Figurine Pop Goku Ultra.jpg',GETDATE(),27.90),
('Figurine Pop M Vegeta','goodies','Image/Figurine Pop M Vegeta.jpg',GETDATE(),27.90),
('Figurine Gogeta SS4','goodies','Image/Figurine Gogeta SS4.jpg',GETDATE(),37.80),
('Figurine Broly Fullpower','goodies','Image/Figurine Broly Fullpower.jpg',GETDATE(),37.90),
('Figurine Trunks SS','goodies','Image/Figurine Trunks SS.jpg',GETDATE(),39.90),
('Figurine Freezer','goodies','Image/Figurine Freezer.jpg',GETDATE(),7.80),
('Figurine Son Goku SS3','goodies','Image/Figurine Son Goku SS3.jpg',GETDATE(),39.90),
('Figurines Goku UI Vs Jiren','goodies','Image/Figurines Goku UI Vs Jiren Match Makers.jpg',GETDATE(),67.80),
('Figurine Majin Buu','goodies','Image/Figurine Majin Buu.jpg',GETDATE(),37.80),
('Figurines Goten Trunks Fusion','goodies','Image/Figurines Goten Trunks Fusion.jpg',GETDATE(),49.80),
('Figurine Gotenks SS Ghost','goodies','Image/Figurine Gotenks SS Ghost.jpg',GETDATE(),39.80),
('Figurine Gotenks SS3','goodies','Image/Figurine Gotenks SS3.jpg',GETDATE(),47.80),
('Figurine Son Goku SSG','goodies','Image/Figurine Son Goku SSG.jpg',GETDATE(),47.80),
('Figurine Son Goku SSB','goodies','Image/Figurine Son Goku SSB.jpg',GETDATE(),47.80),
('Figurine Vegeta SSB','goodies','Image/Figurine Vegeta SSB.jpg',GETDATE(),47.80),
('Figurine Baby Vegeta SS2','goodies','Image/Figurine Baby Vegeta SS2.jpg',GETDATE(),47.80),
('Figurine Vegeto SS','goodies','Image/Figurine Vegeto SS.jpg',GETDATE(),59.80),
('Figurine Gogeta SS','goodies','Image/Figurine Gogeta SS.jpg',GETDATE(),47.80),
('Figurine Broly SS2','goodies','Image/Figurine Broly SS2.jpg',GETDATE(),47.80),
('Figurine Metal Cooler','goodies','Image/Figurine Metal Cooler.jpg',GETDATE(),43.80),
('Figurine Black Goku','goodies','Image/Figurine Black Goku.jpg',GETDATE(),47.80),
('Figurine Beerus','goodies','Image/Figurine Beerus.jpg',GETDATE(),47.80),
('Figurines Gohan Enfant SS2 Vs Cell','goodies','Image/Figurines Gohan Enfant SS2 Vs Cell Match Makers.jpg',GETDATE(),67.80),
('Figurines Gogeta Vs Janemba','goodies','Image/Figurines Gogeta Janemba Match Makers.jpg',GETDATE(),67.80),
('Tapis de Bureau Dragon Ball Super','goodies','Image/Tapis de Bureau DBS.jpg',GETDATE(),25.80),
('Sac Dragon Ball Super','goodies','Image/Sac DBS.jpg',GETDATE(),18.80),
('Sac de Sport Dragon Ball Z','goodies','Image/Sac de Sport DBZ.jpg',GETDATE(),35.80),
('Sac à Dos Goku','goodies','Image/Sac à Dos Goku.jpg',GETDATE(),29.80),
('Puzzle 1000 Pieces Dragon Ball Z','goodies','Image/Puzzle 1000 Pieces DBZ.jpg',GETDATE(),55.80),
('Jeu de 54 Cartes Dragon Ball Z','goodies','Image/Jeu de 54 Cartes DBZ.jpg',GETDATE(),25.80),
('Uno Dragon Ball Z','goodies','Image/Uno DBZ.jpg',GETDATE(),45.80),
('Jeu de 7 Familles Dragon Ball Z','goodies','Image/Jeu de 7 Familles DBZ.jpg',GETDATE(),25.80),
('Boite à Musique Tapion','goodies','Image/Boite à Musique Tapion DBZ.jpg',GETDATE(),59.80),
('Coffret 7 Boules de Cristal Dragon Ball Z','goodies','Image/Coffret 7 Boules de Cristal DBZ.jpg',GETDATE(),75.80),
('Boule de Cristal 2 Etoiles Dragon Ball Z','goodies','Image/Boule De Cristal DBZ.jpg',GETDATE(),21.80),
('Mug Thermique Gohan vs Cell','goodies','Image/Mug Thermique Gohan Vs Cell.jpg',GETDATE(),25.80),
('Mug Broly SS2','goodies','Image/Mug Broly SS2.jpg',GETDATE(),21.80),
('Mug Goku','goodies','Image/Mug Goku.jpg',GETDATE(),21.80),
('Mug Hit','goodies','Image/Mug Hit.jpg',GETDATE(),21.80),
('Boite à Cookies Kamehouse Dragon Ball Z','goodies','Image/Boite à Cookies Kamehouse DBZ.jpg',GETDATE(),75.80),
('Porte Cle Goku SSB','goodies','Image/Porte Cle Goku SSB.jpg',GETDATE(),11.80),
('Porte Cle Pop Goku SS4','goodies','Image/Porte Cle Pop Goku SS4.jpg',GETDATE(),15.80),
('Porte Cle Radar Dragon Ball Z','goodies','Image/Porte Cle Radar DBZ.jpg',GETDATE(),11.80),
('Peluche Nuage Magique Dragon Ball Z','goodies','Image/Peluche Nuage Magique DBZ.jpg',GETDATE(),33.80),
('Lots Figurines Dragon Ball Z','goodies','Image/Lots Figurines DBZ.jpg',GETDATE(),55.80),
('Bol Chapeau Luffy','vaisselle','Image/Bol Chapeau Luffy.jpg',GETDATE(),37.90),
('Mug One Piece','vaisselle','Image/Mug One piece.jpg',GETDATE(),35.90),
('Tasse et Bol One Piece','vaisselle','Image/Tasse et Bol One Piece.jpg',GETDATE(),45.50),
('Bol Drapeau One Piece','vaisselle','Image/Bol Drapeau One Piece.jpg',GETDATE(),35.80),
('Assiette One Piece','vaisselle','Image/Assiette One Piece.jpg',GETDATE(),220.90),
('Mug Thermique One Piece Wanted','vaisselle','Image/Mug Thermique One Piece Wanted.jpg',GETDATE(),38.80),
('Mug Luffy Gear 5 Attaque','vaisselle','Image/Mug Luffy Gear 5 Attaque.jpg',GETDATE(),27.90),
('Mug Monkey D Luffy','vaisselle','Image/Mug Monkey D Luffy.jpg',GETDATE(),27.80),
('Mug Luffy Zoro Chopper','vaisselle','Image/Mug Luffy Zoro Chopper.jpg',GETDATE(),27.80),
('Mug Chopper','vaisselle','Image/Mug Chopper.jpg',GETDATE(),27.80),
('Mug Garp','vaisselle','Image/Mug Garp.jpg',GETDATE(),27.80),
('Mug Barbe Noir','vaisselle','Image/Mug Barbe Noir.jpg',GETDATE(),27.80),
('Mug Trafalgar Law','vaisselle','Image/Mug Trafalgar Law.jpg',GETDATE(),27.80),
('Bol Konoha','vaisselle','Image/Bol Konoha.jpg',GETDATE(),32.80),
('Bol Akatsuki','vaisselle','Image/Bol Akatsuki.jpg',GETDATE(),32.80),
('Verre Akatsuki','vaisselle','Image/Verre Akatsuki.jpg',GETDATE(),35.80),
('Verre Uchiha','vaisselle','Image/Verre Uchiha.jpg',GETDATE(),35.80),
('Mug Thermique Sasuke Uchiha','vaisselle','Image/Mug Thermique Sasuke.jpg',GETDATE(),38.80),
('Mug Naruto Kakashi','vaisselle','Image/Mug Naruto.jpeg',GETDATE(),27.80),
('Mug Kunai Konoha','vaisselle','Image/Mug Kunai Konoha.jpg',GETDATE(),32.80),
('Mug Sceau Naruto','vaisselle','Image/Mug Sceau Naruto.jpg',GETDATE(),27.80),
('Boite Repas Dragon Ball Z','vaisselle','Image/Boite Alimentaire Dragon Ball Z.jpg',GETDATE(),58.80),
('Verre Vegeta','vaisselle','Image/Verre Vegeta.jpg',GETDATE(),35.80),
('Assiette Dragon Ball Z','vaisselle','Image/Assiette Dragon Ball Z.jpg',GETDATE(),42.80),
('Assiette Son Goku','vaisselle','Image/Assiette Son Goku.jpg',GETDATE(),42.80),
('Mug Dragon Ball Z','vaisselle','Image/Mug Dragon Ball Z.jpg',GETDATE(),27.80),
('Kit Anniversaire Demon Slayer','vaisselle','Image/Kit Anniversaire Demon Slayer.jpg',GETDATE(),127.80),
('Bol Tanjiro','vaisselle','Image/Bol Tanjiro.png',GETDATE(),32.80),
('Verre Demon Slayer','vaisselle','Image/Verre Demon Slayer.jpg',GETDATE(),35.80),
('Verre Itadori Sukuna','vaisselle','Image/Verre Itadori Sukuna.jpg',GETDATE(),35.80),
('Mug Doigt Sukuna','vaisselle','Image/Mug Doigt Sukuna.jpg',GETDATE(),32.80),
('Mug Nezuko Demon','vaisselle','Image/Mug Nezuko Demon.jpg',GETDATE(),27.80),
('Mug Tanjiro Zenitsu','vaisselle','Image/Mug Tanjiro Zenitsu.jpg',GETDATE(),27.80),
('Mug Mitsuri Kanroji','vaisselle','Image/Mug Mitsuri Kanroji.jpg',GETDATE(),27.80),
('Mug Nezuko','vaisselle','Image/Mug Nezuko.jpg',GETDATE(),27.80),
('Mug Tanjiro','vaisselle','Image/Mug Tanjiro.jpg',GETDATE(),27.80),
('Mug Tomyoka','vaisselle','Image/Mug Tomyoka.jpg',GETDATE(),27.80),
('Bol Pokemon','vaisselle','Image/Bol Pokemon.jpg',GETDATE(),32.80),
('Mug Pikachu','vaisselle','Image/Mug Pikachu.jpg',GETDATE(),27.80),
('Bol Death Note','vaisselle','Image/Bol Death Note.jpg',GETDATE(),32.80),
('Mug L','vaisselle','Image/Mug L.jpg',GETDATE(),27.80),
('Verre Tokyo Ghoul','vaisselle','Image/Verre Tokyo Ghoul.jpg',GETDATE(),35.80),
('Mug Tokyo Ghoul','vaisselle','Image/Mug Tokyo Ghoul.jpg',GETDATE(),27.80),
('Tasse et Bol My Hero Academia','vaisselle','Image/Tasse et Bol My Hero Academia.jpg',GETDATE(),45.80),
('Mug Saitama','vaisselle','Image/Mug Saitama.jpg',GETDATE(),27.80),
('Mug Dandadan','vaisselle','Image/Mug Dandadan.jpg',GETDATE(),27.80),
('Mug Assasination Classroom','vaisselle','Image/Mug Assasination Classroom.jpg',GETDATE(),27.80),
('Mug Spy Family','vaisselle','Image/Mug Spy Family.jpg',GETDATE(),27.80),
('Mug Sailor Moon','vaisselle','Image/Mug Sailor Moon.jpg',GETDATE(),27.80),
('Veste Luffy','textiles','Image/Veste Luffy.jpg',GETDATE(),147.90),
('Veste One Piece','textiles','Image/Veste Symbole One Piece.jpg',GETDATE(),147.90),
('Jogging One Piece','textiles','Image/Jogging One Piece.jpg',GETDATE(),228.50),
('Sweat Ace','textiles','Image/Sweat Ace.jpg',GETDATE(),87.80),
('Sweat Luffy Gear 5','textiles','Image/Sweat Luffy Gear 5.jpg',GETDATE(),77.80),
('Sweat One Piece','textiles','Image/Sweat Symbole One Piece.jpg',GETDATE(),77.80),
('Tee Shirt Luffy','textiles','Image/Tee Shirt Logo Luffy.jpg',GETDATE(),48.00),
('Pyjama Luffy','textiles','Image/Pyjama Luffy.jpg',GETDATE(),78.00),
('Tenue Luffy','textiles','Image/Tenue Luffy.jpg',GETDATE(),47.50),
('Costume Luffy','textiles','Image/Costume Luffy.jpg',GETDATE(),67.90),
('Costume Nami','textiles','Image/Costume Nami.jpg',GETDATE(),67.90),
('Costume Sanji','textiles','Image/Costume Sanji.jpg',GETDATE(),67.90),
('Costume Trafalgar Law','textiles','Image/Costume Trafalgar Law.jpg',GETDATE(),97.80),
('Parure Luffy Gear 5','textiles','Image/Parure Luffy Gear 5.jpg',GETDATE(),258.00),
('Parure Zoro','textiles','Image/Parure Zoro.jpg',GETDATE(),248.00),
('Parure One Piece','textiles','Image/Parure One Piece.jpg',GETDATE(),238.00),
('Doudoune Akatsuki','textiles','Image/Doudoune Akastsuki.jpg',GETDATE(),78.50),
('Jogging Naruto','textiles','Image/Jogging Naruto.jpg',GETDATE(),158.50),
('Sweat Naruto','textiles','Image/Sweat Naruto.jpg',GETDATE(),68.50),
('Tee Shirt Sasuke','textiles','Image/Tee Shirt Sasuke.jpg',GETDATE(),48.50),
('Pyjama Kurama','textiles','Image/Pyjama Kurama.jpg',GETDATE(),58.50),
('Costume Naruto','textiles','Image/Costume Naruto.jpg',GETDATE(),55.50),
('Costume Itachi','textiles','Image/Costume Itachi.jpg',GETDATE(),55.50),
('Parure Naruto','textiles','Image/Parure Naruto.jpg',GETDATE(),258.50),
('Parure Akatsuki','textiles','Image/Parure Akatsuki.jpg',GETDATE(),278.50),
('Parure Sasuke','textiles','Image/Parure Sasuke.jpg',GETDATE(),258.50),
('Veste Black Goku','textiles','Image/Veste Black Goku.jpg',GETDATE(),77.90),
('Jogging Dragon Ball Z','textiles','Image/Jogging Dragon Ball Z.jpg',GETDATE(),127.90),
('Sweat San Goku Ultra Instinct','textiles','Image/Sweat San Goku Ultra Instinct.jpg',GETDATE(),68.50),
('Tee Shirt Gogeta SSB','textiles','Image/Tee Shirt Gogeta SSB.jpg',GETDATE(),47.90),
('Pyjama San Goku','textiles','Image/Pyjama San Goku.jpg',GETDATE(),55.90),
('Costume San Goku','textiles','Image/Costume San Goku.jpg',GETDATE(),50.50),
('Costume Videl','textiles','Image/Costume Videl.jpg',GETDATE(),52.80),
('Parure San Goku Ultra Instinct','textiles','Image/Parure San Goku Ultra Instinct.jpg',GETDATE(),248.50),
('Parure Black Goku','textiles','Image/Parure Black Goku.jpg',GETDATE(),238.50),
('Parure San Goku SS4 Vegeta SS4','textiles','Image/Parure San Goku SS4 Vegeta SS4.jpg',GETDATE(),258.50),
('Veste Zenitsu','textiles','Image/Veste Zeni''tsu.jpg',GETDATE(),75.50),
('Jogging Nezuko','textiles','Image/Jogging Nezuko.jpg',GETDATE(),158.50),
('Sweat Tanjiro','textiles','Image/Sweat Tanjiro.jpg',GETDATE(),65.50),
('Tee Shirt Inosuke','textiles','Image/Tee Shirt Inosuke.jpg',GETDATE(),48.50),
('Pyjama Zenitsu','textiles','Image/Pyjama Zeni''tsu.jpg',GETDATE(),55.50),
('Costume Zenitsu','textiles','Image/Costume Zeni''tsu.jpg',GETDATE(),50.50),
('Costume Nezuko','textiles','Image/Costume Nezuko.jpg',GETDATE(),60.50),
('Parure Demon Slayer','textiles','Image/Parure Demon Slayer.jpg',GETDATE(),258.50),
('Parure Tanjiro Nezuko','textiles','Image/Parure Tanjiro Nezuko.jpg',GETDATE(),268.50),
('Parure Nezuko','textiles','Image/Parure Nezuko.jpg',GETDATE(),278.50),
('Veste One Punch Man','textiles','Image/Veste One Punch Man.jpg',GETDATE(),75.50),
('Jogging Saitama','textiles','Image/Jogging Saitama.jpg',GETDATE(),158.50),
('Sweat Genos','textiles','Image/Sweat Genos.jpg',GETDATE(),65.50),
('Tee Shirt Garou','textiles','Image/Tee Shirt Garou.jpg',GETDATE(),48.50),
('Pyjama Saitama','textiles','Image/Pyjama Saitama.jpg',GETDATE(),55.50),
('Costume Saitama','textiles','Image/Costume Saitama.jpg',GETDATE(),50.50),
('Costume Tatsumaki','textiles','Image/Costume Tatsumaki.jpg',GETDATE(),60.50),
('Parure One Punch Man','textiles','Image/Parure One Punch Man.jpg',GETDATE(),258.50),
('Parure Saitama','textiles','Image/Parure Saitama.jpg',GETDATE(),268.50),
('Parure Genos','textiles','Image/Parure Genos.jpg',GETDATE(),278.50),
('Veste Solo Leveling','textiles','Image/Veste Solo Leveling.jpg',GETDATE(),75.50),
('Jogging Solo Leveling','textiles','Image/Jogging Solo Leveling.jpg',GETDATE(),158.50),
('Sweat Sung Jin Hoo','textiles','Image/Sweat Sung Jin Hoo.jpg',GETDATE(),65.50),
('Tee Shirt Sung Jin Hoo','textiles','Image/Tee Shirt Sung Jin Hoo.jpg',GETDATE(),48.50),
('Pyjama Solo Leveling','textiles','Image/Pyjama Solo Leveling.jpg',GETDATE(),55.50),
('Costume Sung Jin Hoo','textiles','Image/Costume Sung Jin Hoo.jpg',GETDATE(),50.50),
('Costume Cha Hae In','textiles','Image/Costume Cha Hae In.jpg',GETDATE(),60.50),
('Parure Sung Jin Hoo','textiles','Image/Parure Sung Jin Hoo.jpg',GETDATE(),258.50),
('Parure Solo Leveling','textiles','Image/Parure Solo Leveling.jpg',GETDATE(),268.50),
('Parure Sung Jin Hoo Black','textiles','Image/Parure Sung Jin Hoo Black.jpg',GETDATE(),278.50);

/* ======================================================================================= */
/* ======================================================================================= */

CREATE TABLE orders_articles (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  orders_id INTEGER NOT NULL,
  articles_id INTEGER NOT NULL,
  
  FOREIGN KEY (orders_id) REFERENCES orders(id),
  FOREIGN KEY (articles_id) REFERENCES articles(id)
);

INSERT INTO orders_articles( orders_id, articles_id) VALUES
(1, 2),
(3, 3),
(4, 2),
(5, 1);

/* ======================================================================================= */
/* ======================================================================================= */

/* Base : products (mangas + goodies) */

CREATE TABLE IF NOT EXISTS products (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    author TEXT,
    price REAL NOT NULL,
    image TEXT,
    category TEXT CHECK (category IN ('Historiques', 'Classiques', 'Pépites', 'Goodies')),
    description TEXT
);

/* Tous les items présents dans mon HTML */

INSERT INTO products (title, author, price, image, category) VALUES
('Black Clover - Tome 1', NULL, 7.90, 'Black-Clover-Tome.jpeg', 'Historiques'),
('Demon Slayer Vol. 1', NULL, 12.00, 'Demon-Slayer-Tome.jpeg', 'Historiques'),
('One Piece - Tome 1', NULL, 7.90, 'One-Piece-Tome.jpeg', 'Historiques'),
('Naruto Shippuden - Tome 1', NULL, 7.90, 'Naruto-Shippuden.jpeg', 'Historiques'),
('Dandadan - Tome 1', NULL, 7.90, 'Dandadan-Tome.jpeg', 'Historiques'),
('Solo Leveling - Tome 1', NULL, 8.50, 'Solo-Leveling-Tome.jpeg', 'Historiques'),
('Jujutsu Kaisen - Tome 1', NULL, 7.90, 'Jujutsu-Kaisen-Tome.jpeg', 'Historiques'),
('Death Note - Tome 1', NULL, 6.90, 'Death-Note-Tome.jpeg', 'Historiques'),
('Edens Zero - Tome 1', NULL, 7.90, 'Edens-Zero-Tome.jpeg', 'Historiques'),
('One Punch Man - Tome 1', NULL, 7.90, 'One-Punch-Man-Tome.jpeg', 'Historiques'),
('Sakamoto Days - Tome 1', NULL, 7.90, 'Sakamoto-Days-Tome.jpeg', 'Historiques'),
('Full Metal Alchemist - Tome 1', NULL, 7.90, 'Full-Metal-Tome.jpeg', 'Historiques'),

-- Classiques
('Dragon Ball - Tome 1', NULL, 6.90, 'Dragon-Ball-Tome.jpeg', 'Classiques'),
('Dragon Ball Z - Tome 1', NULL, 7.10, 'Dragon-Ball-Z-Tome.jpeg', 'Classiques'),
('One Piece - Tome 1', NULL, 6.90, 'One-Piece-Tome.jpeg', 'Classiques'),
('Naruto - Tome 1', NULL, 7.50, 'Naruto-Tome.jpeg', 'Classiques'),
('Naruto Shippuden - Tome 1', NULL, 7.90, 'Naruto-Shippuden.jpeg', 'Classiques'),
('Bleach - Tome 1', NULL, 7.30, 'Bleach-Tome.jpeg', 'Classiques'),
('Pokémon - Tome 1', NULL, 6.50, 'Pokemon-Tome.jpeg', 'Classiques'),
('Sailor Moon - Tome 1', NULL, 8.00, 'Sailor-Moon-Tome.jpeg', 'Classiques'),
('Ranma ½ - Tome 1', NULL, 7.40, 'Ranma-1-2-Tome.jpeg', 'Classiques'),
('Détective Conan - Tome 1', NULL, 7.60, 'Détective-Conan-Tome.jpeg', 'Classiques'),
('Yu-Gi-Oh - Tome 1', NULL, 7.00, 'Yu-Gi-Oh-Tome.jpeg', 'Classiques'),
('Great Teacher Onizuka - Tome 1', NULL, 8.20, 'Great-Teacger-Onizuka-Tome.jpeg', 'Classiques'),

-- Pépites
('Hajime No Ippo - Tome 1', NULL, 8.90, 'Hajime-No-Ippo-Tome.jpeg', 'Pépites'),
('Saint Seiya - Tome 1', NULL, 7.20, 'Saint-Seya-Tome.jpeg', 'Pépites'),
('Ken le Survivant - Tome 1', NULL, 8.50, 'Ken-Le-Survivant-Tome.jpeg', 'Pépites'),
('City Hunter - Tome 1', NULL, 7.60, 'City-Hunter-Tome.jpeg', 'Pépites'),
('Gundam Wing - Tome 1', NULL, 8.00, 'Gundam-Wing-Tome.jpeg', 'Pépites'),
('Fairy Tail - Tome 1', NULL, 7.50, 'Fairy-Tail-Tome.jpeg', 'Pépites'),
('Afro Samouraï - Tome 1', NULL, 9.10, 'Afro-Samourai-Tome.jpeg', 'Pépites'),
('99 Renforced Wooden Stick', NULL, 10.00, '99-Renforced-Wooden-Stick.jpeg', 'Pépites'),
('Moi Slime - Tome 1', NULL, 7.80, 'Moi-Slime-Tome.jpeg', 'Pépites'),

-- Goodies (images et items visibles dans ta section Goodies)
('Figurine Aokiji', NULL, 25.00, 'Gif-figurine-Aokiji.gif', 'Goodies'),
('Mug Dragon Ball Z', NULL, 12.00, 'Gif-Mug-Bdz.webp', 'Goodies'),
('Lot de figurine', NULL, 180.00, 'Gif-Figurine.webp', 'Goodies'),
('Mug Sasuke', NULL, 12.50, 'Gif-Mug-Sasuke.webp', 'Goodies'),
('Figurine Alma Feri', NULL, 20.00, 'Gif-Figurine2.gif', 'Goodies'),
('Mug Yu-Gi-Oh', NULL, 14.00, 'Mug-YuGiOh-thermo-actif.gif', 'Goodies'),
('Figurine Terrece', NULL, 22.00, 'Gif-Figurine-3.webp', 'Goodies'),
('Produit Naruto (banner)', NULL, 0.00, 'Produit-Naruto.jpeg', 'Goodies'),
('Produit Jujutsu-Kaisen (banner)', NULL, 0.00, 'Produit-Jujutsu-Kaisen.jpeg', 'Goodies'),
('Produit One Piece (banner)', NULL, 0.00, 'Produit-One-Piece.jpeg', 'Goodies'),
('Produit Demon Slayer (banner)', NULL, 0.00, 'Produit-Demon-Slayer.jpeg', 'Goodies'),
('Produit DBZ (banner)', NULL, 0.00, 'Produit-DBZ.jpeg', 'Goodies');


/* ======================================================================================= */
/* ======================================================================================= */

CREATE TABLE contact (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  users_id INTEGER NOT NULL,
  sujet VARCHAR(20) NOT NULL,  
  message TEXT NOT NULL,
  message_date DATE NOT NULL,
  status VARCHAR(15) NOT NULL CHECK (status IN ('en attente', 'lu', 'repondu')),

  FOREIGN KEY (users_id) REFERENCES user(id)
);

INSERT INTO contact (users_id, sujet, message, message_date, status) VALUES 
(2, 'Commande', 'Je n''ai toujours pas reçu ma commande', '2025-05-10', 'repondu'),
(3, 'Commande', 'Ma commande est détérioré. Que faire', '2025-05-10', 'repondu'),
(4, 'Commande', 'Trés satisfait arrivé rapidement', '2025-05-10', 'lu'),
(5, 'Commande', 'Super j''ai reçu ma commande', '2025-05-10', 'lu'),
(6, 'Commande', 'Trés bon site merci', '2025-05-10', 'en attente'),
(7, 'Commande', 'Je n''ai toujours pas reçu ma commande', '2025-05-10', 'en attente');

/* ======================================================================================= */
/* ======================================================================================= */
