PRAGMA foreign_keys = ON;

DROP TABLE IF EXISTS contact;
DROP TABLE IF EXISTS orders_articles;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS articles;
DROP TABLE IF EXISTS user;


CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  phone TEXT UNIQUE,
  address TEXT,
  city TEXT,
  role TEXT NOT NULL CHECK (role IN ('user', 'admin')),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO user (first_name, last_name, email, password, phone, address, city, role) VALUES
('Mato', 'NGUAYILA', 'matomina.nguayila@gmail.com', 'Orly94', '07-54-69-32-58', '1 rue du clos dion', 'Montereau-Fault-Yonne', 'admin'),
('Cynthia', 'DAUVERNE', 'cynthia.dauverne@gmail.com', 'Monterau77', '07-55-69-32-58', '1 rue du clos dion', 'Montereau-Fault-Yonne', 'user'),
('Hakim', 'BOUDERE', 'hakim.boudere@gmail.com', 'Paris75', '07-56-69-32-58', '1 rue de la paix', 'Paris', 'user'),
('Billal', 'ZEBIR', 'billal.zerbir@gmail.com', 'Pantin93', '07-57-69-32-58', '1 rue de courcelle', 'Pantin', 'user'),
('Zeyna', 'SIDIBE', 'zeyna.sidibe@gmail.com', 'Cachan94', '07-58-69-32-58', '1 rue pasteur', 'Cachan', 'user'),
('Alfred', 'Macdy', 'alfred.macdy@gmail.com', 'Evry91', '07-59-69-32-58', '1 allée de la brume', 'Evry', 'user'),
('Moussa', 'DIOP', 'moussa.diop@gmail.com', 'Coulommier77', '07-60-69-32-58', '1 rue des champs', 'Coulommiers', 'user');

/* ======================================================================================= */
/* ======================================================================================= */

CREATE TABLE articles (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  genres TEXT NOT NULL CHECK (genres IN ('manga', 'figurine', 'textiles','vaisselle', 'goodies')),
  image TEXT NOT NULL,
  price REAL NOT NULL,
  stock INTEGER NOT NULL DEFAULT 10,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO articles (name, genres, image, price) VALUES 
('Dragon Ball','manga','image/Dragon-Ball-Tome.jpeg', 6.90),
('Dragon Ball Z','manga','image/Dragon-Ball-Z-Tome.jpeg', 7.10),
('One Piece','manga','image/One-Piece-Tome.jpeg', 6.90),
('Naruto','manga','image/Naruto-Tome.jpeg', 7.50),
('Naruto Shippuden','manga','image/Naruto-Shippuden.jpeg', 7.90),
('Bleach','manga','image/Bleach-Tome.jpeg', 7.30),
('Pokémon','manga','image/Pokemon-Tome.jpeg', 6.50),
('Sailor Moon','manga','image/Sailor-Moon-Tome.jpeg', 8.00),
('Ranma ½','manga','image/Ranma-1-2-Tome.jpeg', 7.40),
('Détective Conan','manga','image/Détective-Conan-Tome.jpeg', 7.60),
('Yu-Gi-Oh','manga','image/Yu-Gi-Oh-Tome.jpeg', 7.00),
('Great Teacher Onizuka','manga','image/Great-Teacher-Onizuka-Tome.jpeg', 8.20),
('Death Note','manga','image/Death-Note-Tome.jpeg', 6.90),
('Hajime No Ippo','manga','image/Hajime-No-Ippo-Tome.jpeg', 8.90),
('Saint Seiya','manga','image/Saint-Seya-Tome.jpeg', 7.20),
('Ken le Survivant','manga','image/Ken-Le-Survivant-Tome.jpeg', 8.50),
('City Hunter','manga','image/City-Hunter-Tome.jpeg', 7.60),
('Gundam Wing','manga','image/Gundam-Wing-Tome.jpeg', 8.00),
('Full Metal Alchemist','manga','image/Full-Metal-Tome.jpeg', 8.00),
('Fairy Tail','manga','image/Fairy-Tail-Tome.jpeg', 7.50),
('One Punch Man','manga','image/One-Punch-Man-Tome.jpeg', 8.50),
('Afro Samouraï','manga','image/Afro-Samourai-Tome.jpeg', 9.10),
('99 Renforced Wooden Stick','manga','image/99-Renforced-Wooden-Stick.jpeg', 10.00),
('Moi Slime','manga','image/Moi-Slime-Tome.jpeg', 7.80),
('Figurine Aokiji','goodies','image/Gif-figurine-Aokiji.gif', 25.00),
('Mug Dragon Ball Z','goodies','image/Gif-Mug-Bdz.webp', 12.00),
('Lot de figurine','goodies','image/Gif-Figurine.webp', 180.00),
('Mug Sasuke','goodies','image/Gif-Mug-Sasuke.webp', 12.50),
('Figurine Alma Feri','goodies','image/Gif-Figurine2.gif', 20.00),
('Mug Yu-Gi-Oh','goodies','image/Mug-YuGiOh-thermo-actif.gif', 14.00),
('Figurine Terrece','goodies','image/Gif-Figurine-3.webp', 22.00),
('One Piece','manga','image/One-Piece-Tome.jpeg', 7.80),
('Naruto-Shippuden','manga','image/Naruto-Shippuden.jpeg', 7.80),
('Jujutsu-Kaisen','manga','image/Jujutsu-Kaisen-Tome.jpeg', 7.80),
('Demon-Slayer','manga','image/Demon-Slayer-Tome.jpeg', 7.80),
('Black-Clover','manga','image/Black-Clover-Tome.jpeg', 7.80),
('Death-Note','manga','image/Death-Note-Tome.jpeg', 7.80),
('Solo-Leveling','manga','image/Solo-Leveling-Tome.jpeg', 7.80),
('My-Hero-Academia','manga','image/My-Hero-Academia-Tome.jpeg', 7.80),
('Hajime-No-Ippo','manga','image/Hajime-No-Ippo-Tome.jpeg', 7.80),
('Kaiju-N°8','manga','image/Kaiju-N°8-Tome.jpeg', 7.80),
('Dandadan','manga','image/Dandadan-Tome.jpeg', 7.80),
('Edens-Zero','manga','image/Edens-Zero-Tome.jpeg', 7.80),
('Sakamoto-Days','manga','image/Sakamoto-Days-Tome.jpeg', 7.80),
('One-Punch-Man','manga','image/One-Punch-Man-Tome.jpeg', 7.80),
('Full-Metal','manga','image/Full-Metal-Tome.jpeg', 7.80),
('Dr-Stone','manga','image/Dr-Stone-Tome.jpeg', 7.80),
('Afro-Samourai','manga','image/Afro-Samourai-tome.jpeg', 7.80),
('Fairy-Tail','manga','image/Fairy-Tail-Tome.jpeg', 7.80),
('Hunter-X-Hunter','manga','image/Hunter-X-Hunter-Tome.jpeg', 7.80),
('99-Renforced-Wooden-Stick','manga','image/99-Renforced-Wooden-Stick.jpeg', 7.80),
('Moi-Quand-Je-Me-Reincarne-En-Slime','manga','image/Moi-Slime-Tome.jpeg', 7.80),
('Gundam-Wing','manga','image/Gundam-Wing-Tome.jpeg', 7.80),
('City-Hunter- Nicky-Larson','manga','image/City-Hunter-Tome.jpeg', 7.80),
('Ranma1/2','manga','image/Ranma-1-2-Tome.jpeg', 7.80),
('Shangri-La-Frontier','manga','image/Shangri-La-Frontier.jpeg', 7.80),
('Gachiakuta','manga','image/Gachiakuta-Tome.jpeg', 7.80),
('Great-Teacher-Onizuka','manga','image/Great-Teacger-Onizuka-Tome.jpeg', 7.80),
('Yu-Gi-Oh','manga','image/Yu-Gi-Oh-Tome.jpeg', 7.80),
('Détective-Conan','manga','image/Détective-Conan-Tome.jpeg', 7.80),
('Ken-Le-Survivant','manga','image/Ken-Le-Survivant-Tome.jpeg', 7.80),
('Saint-Seya-Les-Chevaliers-Du-Zodiaque','manga','image/Saint-Seya-Tome.jpeg', 7.80),
('Sailor-Moon','manga','image/Sailor-Moon-Tome.jpeg', 7.80),
('Dragon-Ball-Z','manga','image/Dragon-Ball-Z-Tome.jpeg', 7.80),
('Naruto','manga','image/Naruto-Tome.jpeg', 7.80),
('Dragon-Ball','manga','image/Dragon-Ball-Tome.jpeg', 7.80),
('Bleach','manga','image/Bleach-Tome.jpeg', 7.80),
('Pop Naruto - Edition limitée','goodies','image/Pop Naruto.jpeg', 29.90),
('Figurine Itachi + Peluche Kuruma','goodies','image/Figurine Itachi + Peluche Kuruma.jpeg', 52.50),
('Figurine Jiraya','goodies','image/Figurine Jiraya.jpeg', 25.90),
('Figurine Naruto Mode Emite','goodies','image/Figurine Naruto Mode Emite.jpeg', 35.90),
('Mug Naruto Kakashi','goodies','image/Mug Naruto.jpg', 9.90),
('Jeu de société Naruto','goodies','image/Jeu de société Naruto.jpeg', 56.50),
('Katana Konoha','goodies','image/Katana Naruto.jpeg', 74.90),
('Sac Naruto','goodies','image/Sac Naruto.jpeg', 34.90),
('Porte clé Pop Naruto','goodies','image/Porte clé Pop Naruto.jpeg', 14.90),
('Mug Naruto Equipe 7','goodies','image/Mug Naruto Equipe 7.jpeg', 9.90),
('Bandeau Sasuke','goodies','image/Bandeau Naruto.jpeg', 44.90),
('Kunai Naruto','goodies','image/Kunai Naruto.jpeg', 54.90),
('Figurine Satoru Gojo','goodies','image/Figurine Satoru Gojo.jpeg', 17.80),
('Lampe Satoru Gojo','goodies','image/Lampe Satoru Gojo.jpeg', 27.80),
('Mug Itadori','goodies','image/Mug Itadori 1.jpg', 9.80),
('Figurine Pop Sukuna','goodies','image/Figurin Pop Sukuna.jpeg', 27.80),
('Sac à Dos Jujutsu Kaisen','goodies','image/Sac à Dos Jujutsu Kaisen.jpeg', 47.80),
('Lots Bagues Jujutsu Kaisen','goodies','image/Lots Bagues Jujutsu Kaisen.jpeg', 37.80),
('Figurine Pop Megumi','goodies','image/Figurine Pop Megumi.jpeg', 27.80),
('Lots Porte Clé Jujutsu Kaisen','goodies','image/Lots Porte Clé Jujutsu Kaisen.jpeg', 17.80),
('Mug Satoru Gojo','goodies','image/Mug Satoru Gojo.jpeg', 18.80),
('Figurine Led Luffy Gear 5','goodies','image/Figurine Led Luffy Gear 5.jpeg', 67.80),
('Bateau Thousant Sunny','goodies','image/Bateau Thousant Sunny.jpeg', 87.80),
('Coffre au Trésor One Piece','goodies','image/Coffre au Trésor One Piece.jpeg', 97.80),
('Figurine Pop Luffy','goodies','image/Figurine Pop Luffy.jpeg', 27.80),
('Figurine Ace','goodies','image/Figurine Ace.jpeg', 27.80),
('Verre One Piece','goodies','image/Verre One Piece.jpeg', 7.80),
('Figure Jinbe','goodies','image/Figure Jinbe.jpeg', 37.80),
('Figurine Ener','goodies','image/Figurine Ener.jpeg', 37.80),
('Fruits des Demons','goodies','image/Fruits des Demons.jpeg', 47.80),
('Figurine Pop Kaido','goodies','image/Figurine Pop Kaido.jpeg', 27.80),
('Figurine Luffy Gear 5','goodies','image/Figurine Luffy Gear 5.jpeg', 39.80),
('Figurine Mihawk','goodies','image/Figurine Mihawk.jpeg', 39.80),
('Figurine Pop Zoro','goodies','image/Figurine Pop Zoro.jpeg', 27.80),
('Figurine Barbe Noir','goodies','image/Figurine Barbe Noir.jpeg', 37.80),
('Peluche Fruit du Démon','goodies','image/Peluche Fruit du Demon.jpeg', 29.80),
('Chapeau Luffy','goodies','image/Chapeau Luffy.jpeg', 54.80),
('Support Portable Luffy Gear 5','goodies','image/Support Portable Luffy Gear 5.jpeg', 25.80),
('Coque Portable One Piece','goodies','image/Coque Portable.jpeg', 17.80),
('Sac à Dos One Piece','goodies','image/Sac à Dos One Piece.jpeg', 45.80),
('Lots Mugs One Piece','goodies','image/Lots Mugs One Piece.jpeg', 77.80),
('Lampe Luffy Gear 5','goodies','image/Lampe Luffy Gear 5.jpeg', 44.80),
('Figurine Gear 5 Luffy','goodies','image/Figurine Gear 5 Luffy.jpg', 55.80),
('Figurine Gol D Roger','goodies','image/Figurine Gol D Roger.jpeg', 44.80),
('Bague One Piece','goodies','image/Bague One Piece.jpeg', 25.80),
('Porte Feuille One Piece','goodies','image/Porte Feuille One Piece.jpeg', 45.80),
('Manette PS5 One Piece','goodies','image/Manette PS5 One Piece.jpeg', 125.80),
('Figurine Tanjiro','goodies','image/Figurine Tenjuro.jpeg', 37.90),
('Figurine Pop Tanjiro Nezuko','goodies','image/Figurine Pop Tanjiro Nezuko.jpeg', 39.80),
('Lots Portes Clés Demon Slayer','goodies','image/Lots Porte Clé Demon Slayer.jpeg', 27.80),
('Figurine Nezuko','goodies','image/Figurine Nezuko.jpeg', 29.90),
('Figurine Inosuke','goodies','image/Figurine Inosuke.jpeg', 29.80),
('Katana Tanjiro','goodies','image/Katana Tanjiro.jpg', 107.80),
('Figurine Sabito','goodies','image/Figurine Sabito.jpeg', 29.80),
('Figurine Tengen','goodies','image/Figurine Tengen.jpeg', 29.80),
('Figurine Tomyoka','goodies','image/Figurine Tomyoka.jpeg', 29.80),
('Figurine Muichiro','goodies','image/Figurine Muichiro.jpeg', 29.80),
('Figurine Sanemi','goodies','image/Figurine Sanemi.jpeg', 29.80),
('Figurine Kanroji','goodies','image/Figurine Kanroji.jpg', 29.80),
('Figurine Zenitsu','goodies','image/Figurine Zenitsu.jpeg', 29.80),
('Coffret 15 Piece Demon Slayer','goodies','image/Coffret 15 Piece Demon Slayer.jpeg', 79.80),
('Coffret Demon Slayer','goodies','image/Coffret Demon Slayer.jpeg', 59.80),
('Figurine Pop Nezuko','goodies','image/Figurine Pop Nezuko.jpeg', 29.80),
('Figurine Pop Tanjiro Feu','goodies','image/Figurine Pop Tanjiro Feu.jpeg', 29.80),
('Figurine Pop Kiojuro','goodies','image/Figurine Kiojuro.jpeg', 29.80),
('Figurine Pop Tanjiro','goodies','image/Figurine Pop Tanjiro.jpeg', 29.80),
('Figurine Pop Goku Ultra Instinct','goodies','image/Figurine Pop Goku Ultra.jpg', 27.90),
('Figurine Pop M Vegeta','goodies','image/Figurine Pop M Vegeta.jpg', 27.90),
('Figurine Gogeta SS4','goodies','image/Figurine Gogeta SS4.jpg', 37.80),
('Figurine Broly Fullpower','goodies','image/Figurine Broly Fullpower.jpg', 37.90),
('Figurine Trunks SS','goodies','image/Figurine Trunks SS.jpg', 39.90),
('Figurine Freezer','goodies','image/Figurine Freezer.jpg', 7.80),
('Figurine Son Goku SS3','goodies','image/Figurine Son Goku SS3.jpg', 39.90),
('Figurines Goku UI Vs Jiren','goodies','image/Figurines Goku UI Vs Jiren Match Makers.jpg', 67.80),
('Figurine Majin Buu','goodies','image/Figurine Majin Buu.jpg', 37.80),
('Figurines Goten Trunks Fusion','goodies','image/Figurines Goten Trunks Fusion.jpg', 49.80),
('Figurine Gotenks SS Ghost','goodies','image/Figurine Gotenks SS Ghost.jpg', 39.80),
('Figurine Gotenks SS3','goodies','image/Figurine Gotenks SS3.jpg', 47.80),
('Figurine Son Goku SSG','goodies','image/Figurine Son Goku SSG.jpg', 47.80),
('Figurine Son Goku SSB','goodies','image/Figurine Son Goku SSB.jpg', 47.80),
('Figurine Vegeta SSB','goodies','image/Figurine Vegeta SSB.jpg', 47.80),
('Figurine Baby Vegeta SS2','goodies','image/Figurine Baby Vegeta SS2.jpg', 47.80),
('Figurine Vegeto SS','goodies','image/Figurine Vegeto SS.jpg', 59.80),
('Figurine Gogeta SS','goodies','image/Figurine Gogeta SS.jpg', 47.80),
('Figurine Broly SS2','goodies','image/Figurine Broly SS2.jpg', 47.80),
('Figurine Metal Cooler','goodies','image/Figurine Metal Cooler.jpg', 43.80),
('Figurine Black Goku','goodies','image/Figurine Black Goku.jpg', 47.80),
('Figurine Beerus','goodies','image/Figurine Beerus.jpg', 47.80),
('Figurines Gohan Enfant SS2 Vs Cell','goodies','image/Figurines Gohan Enfant SS2 Vs Cell Match Makers.jpg', 67.80),
('Figurines Gogeta Vs Janemba','goodies','image/Figurines Gogeta Janemba Match Makers.jpg', 67.80),
('Tapis de Bureau Dragon Ball Super','goodies','image/Tapis de Bureau DBS.jpg', 25.80),
('Sac Dragon Ball Super','goodies','image/Sac DBS.jpg', 18.80),
('Sac de Sport Dragon Ball Z','goodies','image/Sac de Sport DBZ.jpg', 35.80),
('Sac à Dos Goku','goodies','image/Sac à Dos Goku.jpg', 29.80),
('Puzzle 1000 Pieces Dragon Ball Z','goodies','image/Puzzle 1000 Pieces DBZ.jpg', 55.80),
('Jeu de 54 Cartes Dragon Ball Z','goodies','image/Jeu de 54 Cartes DBZ.jpg', 25.80),
('Uno Dragon Ball Z','goodies','image/Uno DBZ.jpg', 45.80),
('Jeu de 7 Familles Dragon Ball Z','goodies','image/Jeu de 7 Familles DBZ.jpg', 25.80),
('Boite à Musique Tapion','goodies','image/Boite à Musique Tapion DBZ.jpg', 59.80),
('Coffret 7 Boules de Cristal Dragon Ball Z','goodies','image/Coffret 7 Boules de Cristal DBZ.jpg', 75.80),
('Boule de Cristal 2 Etoiles Dragon Ball Z','goodies','image/Boule De Cristal DBZ.jpg', 21.80),
('Mug Thermique Gohan vs Cell','goodies','image/Mug Thermique Gohan Vs Cell.jpg', 25.80),
('Mug Broly SS2','goodies','image/Mug Broly SS2.jpg', 21.80),
('Mug Goku','goodies','image/Mug Goku.jpg', 21.80),
('Mug Hit','goodies','image/Mug Hit.jpg', 21.80),
('Boite à Cookies Kamehouse Dragon Ball Z','goodies','image/Boite à Cookies Kamehouse DBZ.jpg', 75.80),
('Porte Cle Goku SSB','goodies','image/Porte Cle Goku SSB.jpg', 11.80),
('Porte Cle Pop Goku SS4','goodies','image/Porte Cle Pop Goku SS4.jpg', 15.80),
('Porte Cle Radar Dragon Ball Z','goodies','image/Porte Cle Radar DBZ.jpg', 11.80),
('Peluche Nuage Magique Dragon Ball Z','goodies','image/Peluche Nuage Magique DBZ.jpg', 33.80),
('Lots Figurines Dragon Ball Z','goodies','image/Lots Figurines DBZ.jpg', 55.80),
('Bol Chapeau Luffy','vaisselle','image/Bol Chapeau Luffy.jpg', 37.90),
('Mug One Piece','vaisselle','image/Mug One piece.jpg', 35.90),
('Tasse et Bol One Piece','vaisselle','image/Tasse et Bol One Piece.jpg', 45.50),
('Bol Drapeau One Piece','vaisselle','image/Bol Drapeau One Piece.jpg', 35.80),
('Assiette One Piece','vaisselle','image/Assiette One Piece.jpg', 220.90),
('Mug Thermique One Piece Wanted','vaisselle','image/Mug Thermique One Piece Wanted.jpg', 38.80),
('Mug Luffy Gear 5 Attaque','vaisselle','image/Mug Luffy Gear 5 Attaque.jpg', 27.90),
('Mug Monkey D Luffy','vaisselle','image/Mug Monkey D Luffy.jpg', 27.80),
('Mug Luffy Zoro Chopper','vaisselle','image/Mug Luffy Zoro Chopper.jpg', 27.80),
('Mug Chopper','vaisselle','image/Mug Chopper.jpg', 27.80),
('Mug Garp','vaisselle','image/Mug Garp.jpg', 27.80),
('Mug Barbe Noir','vaisselle','image/Mug Barbe Noir.jpg', 27.80),
('Mug Trafalgar Law','vaisselle','image/Mug Trafalgar Law.jpg', 27.80),
('Bol Konoha','vaisselle','image/Bol Konoha.jpg', 32.80),
('Bol Akatsuki','vaisselle','image/Bol Akatsuki.jpg', 32.80),
('Verre Akatsuki','vaisselle','image/Verre Akatsuki.jpg', 35.80),
('Verre Uchiha','vaisselle','image/Verre Uchiha.jpg', 35.80),
('Mug Thermique Sasuke Uchiha','vaisselle','image/Mug Thermique Sasuke.jpg', 38.80),
('Mug Naruto Kakashi','vaisselle','image/Mug Naruto.jpeg', 27.80),
('Mug Kunai Konoha','vaisselle','image/Mug Kunai Konoha.jpg', 32.80),
('Mug Sceau Naruto','vaisselle','image/Mug Sceau Naruto.jpg', 27.80),
('Boite Repas Dragon Ball Z','vaisselle','image/Boite Alimentaire Dragon Ball Z.jpg', 58.80),
('Verre Vegeta','vaisselle','image/Verre Vegeta.jpg', 35.80),
('Assiette Dragon Ball Z','vaisselle','image/Assiette Dragon Ball Z.jpg', 42.80),
('Assiette Son Goku','vaisselle','image/Assiette Son Goku.jpg', 42.80),
('Mug Dragon Ball Z','vaisselle','image/Mug Dragon Ball Z.jpg', 27.80),
('Kit Anniversaire Demon Slayer','vaisselle','image/Kit Anniversaire Demon Slayer.jpg', 127.80),
('Bol Tanjiro','vaisselle','image/Bol Tanjiro.png', 32.80),
('Verre Demon Slayer','vaisselle','image/Verre Demon Slayer.jpg', 35.80),
('Verre Itadori Sukuna','vaisselle','image/Verre Itadori Sukuna.jpg', 35.80),
('Mug Doigt Sukuna','vaisselle','image/Mug Doigt Sukuna.jpg', 32.80),
('Mug Nezuko Demon','vaisselle','image/Mug Nezuko Demon.jpg', 27.80),
('Mug Tanjiro Zenitsu','vaisselle','image/Mug Tanjiro Zenitsu.jpg', 27.80),
('Mug Mitsuri Kanroji','vaisselle','image/Mug Mitsuri Kanroji.jpg', 27.80),
('Mug Nezuko','vaisselle','image/Mug Nezuko.jpg', 27.80),
('Mug Tanjiro','vaisselle','image/Mug Tanjiro.jpg', 27.80),
('Mug Tomyoka','vaisselle','image/Mug Tomyoka.jpg', 27.80),
('Bol Pokemon','vaisselle','image/Bol Pokemon.jpg', 32.80),
('Mug Pikachu','vaisselle','image/Mug Pikachu.jpg', 27.80),
('Bol Death Note','vaisselle','image/Bol Death Note.jpg', 32.80),
('Mug L','vaisselle','image/Mug L.jpg', 27.80),
('Verre Tokyo Ghoul','vaisselle','image/Verre Tokyo Ghoul.jpg', 35.80),
('Mug Tokyo Ghoul','vaisselle','image/Mug Tokyo Ghoul.jpg', 27.80),
('Tasse et Bol My Hero Academia','vaisselle','image/Tasse et Bol My Hero Academia.jpg', 45.80),
('Mug Saitama','vaisselle','image/Mug Saitama.jpg', 27.80),
('Mug Dandadan','vaisselle','image/Mug Dandadan.jpg', 27.80),
('Mug Assasination Classroom','vaisselle','image/Mug Assasination Classroom.jpg', 27.80),
('Mug Spy Family','vaisselle','image/Mug Spy Family.jpg', 27.80),
('Mug Sailor Moon','vaisselle','image/Mug Sailor Moon.jpg', 27.80),
('Veste Luffy','textiles','image/Veste Luffy.jpg', 147.90),
('Veste One Piece','textiles','image/Veste Symbole One Piece.jpg', 147.90),
('Jogging One Piece','textiles','image/Jogging One Piece.jpg', 228.50),
('Sweat Ace','textiles','image/Sweat Ace.jpg', 87.80),
('Sweat Luffy Gear 5','textiles','image/Sweat Luffy Gear 5.jpg', 77.80),
('Sweat One Piece','textiles','image/Sweat Symbole One Piece.jpg', 77.80),
('Tee Shirt Luffy','textiles','image/Tee Shirt Logo Luffy.jpg', 48.00),
('Pyjama Luffy','textiles','image/Pyjama Luffy.jpg', 78.00),
('Tenue Luffy','textiles','image/Tenue Luffy.jpg', 47.50),
('Costume Luffy','textiles','image/Costume Luffy.jpg', 67.90),
('Costume Nami','textiles','image/Costume Nami.jpg', 67.90),
('Costume Sanji','textiles','image/Costume Sanji.jpg', 67.90),
('Costume Trafalgar Law','textiles','image/Costume Trafalgar Law.jpg', 97.80),
('Parure Luffy Gear 5','textiles','image/Parure Luffy Gear 5.jpg', 258.00),
('Parure Zoro','textiles','image/Parure Zoro.jpg', 248.00),
('Parure One Piece','textiles','image/Parure One Piece.jpg', 238.00),
('Doudoune Akatsuki','textiles','image/Doudoune Akastsuki.jpg', 78.50),
('Jogging Naruto','textiles','image/Jogging Naruto.jpg', 158.50),
('Sweat Naruto','textiles','image/Sweat Naruto.jpg', 68.50),
('Tee Shirt Sasuke','textiles','image/Tee Shirt Sasuke.jpg', 48.50),
('Pyjama Kurama','textiles','image/Pyjama Kurama.jpg', 58.50),
('Costume Naruto','textiles','image/Costume Naruto.jpg', 55.50),
('Costume Itachi','textiles','image/Costume Itachi.jpg', 55.50),
('Parure Naruto','textiles','image/Parure Naruto.jpg', 258.50),
('Parure Akatsuki','textiles','image/Parure Akatsuki.jpg', 278.50),
('Parure Sasuke','textiles','image/Parure Sasuke.jpg', 258.50),
('Veste Black Goku','textiles','image/Veste Black Goku.jpg', 77.90),
('Jogging Dragon Ball Z','textiles','image/Jogging Dragon Ball Z.jpg', 127.90),
('Sweat San Goku Ultra Instinct','textiles','image/Sweat San Goku Ultra Instinct.jpg', 68.50),
('Tee Shirt Gogeta SSB','textiles','image/Tee Shirt Gogeta SSB.jpg', 47.90),
('Pyjama San Goku','textiles','image/Pyjama San Goku.jpg', 55.90),
('Costume San Goku','textiles','image/Costume San Goku.jpg', 50.50),
('Costume Videl','textiles','image/Costume Videl.jpg', 52.80),
('Parure San Goku Ultra Instinct','textiles','image/Parure San Goku Ultra Instinct.jpg', 248.50),
('Parure Black Goku','textiles','image/Parure Black Goku.jpg', 238.50),
('Parure San Goku SS4 Vegeta SS4','textiles','image/Parure San Goku SS4 Vegeta SS4.jpg', 258.50),
('Veste Zenitsu','textiles','image/Veste Zeni''tsu.jpg', 75.50),
('Jogging Nezuko','textiles','image/Jogging Nezuko.jpg', 158.50),
('Sweat Tanjiro','textiles','image/Sweat Tanjiro.jpg', 65.50),
('Tee Shirt Inosuke','textiles','image/Tee Shirt Inosuke.jpg', 48.50),
('Pyjama Zenitsu','textiles','image/Pyjama Zeni''tsu.jpg', 55.50),
('Costume Zenitsu','textiles','image/Costume Zeni''tsu.jpg', 50.50),
('Costume Nezuko','textiles','image/Costume Nezuko.jpg', 60.50),
('Parure Demon Slayer','textiles','image/Parure Demon Slayer.jpg', 258.50),
('Parure Tanjiro Nezuko','textiles','image/Parure Tanjiro Nezuko.jpg', 268.50),
('Parure Nezuko','textiles','image/Parure Nezuko.jpg', 278.50),
('Veste One Punch Man','textiles','image/Veste One Punch Man.jpg', 75.50),
('Jogging Saitama','textiles','image/Jogging Saitama.jpg', 158.50),
('Sweat Genos','textiles','image/Sweat Genos.jpg', 65.50),
('Tee Shirt Garou','textiles','image/Tee Shirt Garou.jpg', 48.50),
('Pyjama Saitama','textiles','image/Pyjama Saitama.jpg', 55.50),
('Costume Saitama','textiles','image/Costume Saitama.jpg', 50.50),
('Costume Tatsumaki','textiles','image/Costume Tatsumaki.jpg', 60.50),
('Parure One Punch Man','textiles','image/Parure One Punch Man.jpg', 258.50),
('Parure Saitama','textiles','image/Parure Saitama.jpg', 268.50),
('Parure Genos','textiles','image/Parure Genos.jpg', 278.50),
('Veste Solo Leveling','textiles','image/Veste Solo Leveling.jpg', 75.50),
('Jogging Solo Leveling','textiles','image/Jogging Solo Leveling.jpg', 158.50),
('Sweat Sung Jin Hoo','textiles','image/Sweat Sung Jin Hoo.jpg', 65.50),
('Tee Shirt Sung Jin Hoo','textiles','image/Tee Shirt Sung Jin Hoo.jpg', 48.50),
('Pyjama Solo Leveling','textiles','image/Pyjama Solo Leveling.jpg', 55.50),
('Costume Sung Jin Hoo','textiles','image/Costume Sung Jin Hoo.jpg', 50.50),
('Costume Cha Hae In','textiles','image/Costume Cha Hae In.jpg', 60.50),
('Parure Sung Jin Hoo','textiles','image/Parure Sung Jin Hoo.jpg', 258.50),
('Parure Solo Leveling','textiles','image/Parure Solo Leveling.jpg', 268.50),
('Parure Sung Jin Hoo Black','textiles','image/Parure Sung Jin Hoo Black.jpg', 278.50);

/* ======================================================================================= */
/* ======================================================================================= */

CREATE TABLE orders (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  total_amount REAL NOT NULL DEFAULT 0,
  status TEXT NOT NULL CHECK (
    status IN ('pending', 'paid', 'shipped', 'delivered', 'cancelled')
  ),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE
);

INSERT INTO orders (user_id, total_amount, status) VALUES
(2, 356, 'pending'),
(2, 250, 'paid'),
(3, 425, 'shipped'),
(4, 99, 'delivered'),
(5, 199, 'cancelled');

/* ======================================================================================= */
/* ======================================================================================= */

CREATE TABLE orders_articles (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  order_id INTEGER NOT NULL,
  article_id INTEGER NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 1,
  unit_price REAL NOT NULL,

  FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  FOREIGN KEY (article_id) REFERENCES articles(id),

  UNIQUE (order_id, article_id)
);

INSERT INTO orders_articles (order_id, article_id, quantity, unit_price) VALUES
(1, 2, 2, 7.10),
(3, 3, 1, 6.90),
(4, 2, 3, 7.10),
(5, 1, 1, 6.90);

/* ======================================================================================= */
/* ======================================================================================= */

CREATE TABLE contact (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER,
  sujet TEXT NOT NULL,
  message TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('pending', 'read', 'answered')) DEFAULT 'pending',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE SET NULL
);

INSERT INTO contact (user_id, sujet, message, status) VALUES
(2, 'Commande', 'Je n''ai toujours pas reçu ma commande', 'answered'),
(3, 'Commande', 'Ma commande est détériorée. Que faire ?', 'answered'),
(4, 'Commande', 'Très satisfait, arrivé rapidement', 'read'),
(5, 'Commande', 'Super j''ai reçu ma commande', 'read'),
(6, 'Commande', 'Très bon site merci', 'pending'),
(7, 'Commande', 'Je n''ai toujours pas reçu ma commande', 'pending');

/* ======================================================================================= */
/* ======================================================================================= */
